### ISSUE TITLE
Mazer install the collection as collection_demo and not demo 

### ISSUE THREAD

**Issue by anshulbehl** [newswangerd/collection_demo#3]
Seeing the README of collection at https://galaxy.ansible.com/newswangerd/collection_demo , all the instructions refer to install under the demo folder and not collection_demo folder.

Which then used directly under and ansible playbook throws cryptic errors like below:

> The offending line appears to be:
> 
>   tasks:
>     - name: Gather some real Facts.
>       ^ here

Installed structure on my end is

> [abehl@ansh collections_bootstrap]$ tree ~/.ansible/collections/ansible_collections/newswangerd
> /home/abehl/.ansible/collections/ansible_collections/newswangerd
> └── collection_demo
>     ├── FILES.json
>     ├── galaxy.yml
>     ├── MANIFEST.json
>     ├── meta
>     ├── plugins
>     │   └── modules
>     │       └── real_facts.py
>     ├── README.md
>     ├── releases
>     │   └── newswangerd-collection_demo-1.0.1.tar.gz
>     └── roles
>         └── factoid
>             ├── meta
>             │   └── main.yaml
>             ├── README.md
>             └── tasks
>                 └── main.yml

Fix needed in tree structure or the sample playbook

**Comment by thaumos** [comment]
@anshulbehl what leads you to believe this collection should be installed by the name demo?

**Comment by anshulbehl** [comment]
@thaumos the documentation present in README of https://galaxy.ansible.com/newswangerd/collection_demo

**Comment by newswangerd** [comment]
When I wrote this, the collection was originally called `demo`. I decided to rename it to `collection_demo` and forgot to update the documentation.
